---
- name: Install packages for dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: no
    
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install packages
  apt: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'git', 'python3-pip']
    state: present
    update_cache: yes
    
- name: Add user to docker group
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Pull Image and Run
  docker_container:
    name: application
    image: greatestfen/ansible-docker:latest
    state: started
    restart_policy: on-failure
    ports:
      - "8080:8080"
