---
# tasks file for appbuild
- name: Copy all files
  copy:
    src: ./
    dest: /home/app/

- name: Start docker service
  service:
    name: docker
    state: started
  
- name: Build an image and push
  docker_image:
    name: greatestfen/ansible-docker:latest
    build:
      path: /home/app
    source: build
